test1: python TestHerinnering1H.py
test2: python TestBevestiging4H.py
test3: python TestFullyAutomation.py
test4: python TEST.py
pw1: python PreWonenBevestiging4H.py
pw2: python PreWonenHerinnering1H.py
pw3: python PreWonenBevestiging.py
pw4: python PreWonenHerinnering.py
vs1: python VestedaBevestiging4H.py
vs2: python VestedaHerinnering1H.py
vs3: python VestedaBevestiging.py
vs4: python VestedaHerinnering.py
